version: "3"
services:
  client:
    container_name: "client"
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/client

    env_file:
      - .env.local


  server:
    container_name: "server"
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    ports:
      - 8888:8888
    volumes:
      - ./src/server:/server
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
